package HW.HW_Day03;

import io.restassured.http.ContentType;
import org.testng.annotations.Test;

import java.util.HashMap;
import java.util.Map;

import static io.restassured.RestAssured.given;
import static org.testng.AssertJUnit.assertEquals;
import static org.testng.AssertJUnit.assertNotNull;

public class HW2 {

    /*
Write an automation test that will create a 'user' using the "https://petstore.swagger.io/" document
*/

    @Test
    public void testCreateUser() {
        // Base URL of the Petstore Swagger API
        String baseUrl = "https://petstore.swagger.io";

        // Define endpoint to create a user
        String createUserEndpoint = "/user";

        // Request body to create a user
        Map<String, Object> userRequestBody = new HashMap<>();
        userRequestBody.put("id", 0); // ID will be generated by the server
        userRequestBody.put("username", "test_user");
        userRequestBody.put("firstName", "abdulaziz");
        userRequestBody.put("lastName", "alghamdi");
        userRequestBody.put("email", "azozalhout2018@gmail.com");
        userRequestBody.put("password", "password123");
        userRequestBody.put("phone", "0542679912");

        // Send POST request to create a user
        io.restassured.response.Response response = given()
                .baseUri(baseUrl)
                .contentType(ContentType.JSON)
                .body(userRequestBody)
                .when()
                .post(createUserEndpoint);

        // Assert response status code
        assertEquals(response.statusCode(), 200);

        // Assert response body
        Map<String, Object> responseBody = response.body().as(Map.class);
        assertNotNull(responseBody.get("code"));
        assertEquals(responseBody.get("message"), "0");
        assertEquals(responseBody.get("type"), "unknown");
    }
}





